# Generated by Django 2.0.3 on 2018-07-09 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Validated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('\\w\\w\\d+', 'Please enter a string starting with two characters, followed by up to 8 numbers')])),
                ('enabled', models.BooleanField()),
                ('amount', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('item_type', models.IntegerField(choices=[(0, 'Choice 1'), (1, 'Choice 2'), (2, 'Choice 3'), (3, 'Choice 4')])),
                ('item_flags', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=4, validators=[django.core.validators.RegexValidator('[ABC]*', 'Only options A-C may be chosen')])),
            ],
        ),
    ]
