# Generated by Django 2.1.7 on 2019-03-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicfields",
            name="float_field",
            field=models.FloatField(null=True),
        ),
    ]
