# Generated by Django 2.2.1 on 2020-02-25 07:29

from django.db import migrations, models

from dynamicforms.dynamicforms_migration import DynamicformsMigration


class Migration(DynamicformsMigration):
    dependencies = [
        ('examples', '0002_auto_20190320_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='name',
            field=models.CharField(blank=True, help_text='Name field', max_length=20, null=True,
                                   verbose_name='Name field'),
        ),
    ]
