# Generated by Django 2.1.1 on 2018-11-27 09:07

from django.db import migrations, models


def add_page_load(apps, schema_editor):
    from ..models import PageLoad
    for i in range(1, 10000 + 1):
        PageLoad.objects.create(description='Item %d' % i)


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0002_dynamic_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Item description', max_length=20)),
            ],
        ),
        migrations.RunPython(add_page_load, lambda apps, schema_editor: None),
    ]
