# Generated by Django 2.2.1 on 2019-11-05 09:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0002_auto_20190320_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(help_text='Action name', max_length=256, verbose_name='Action name')),
                ('action_type', models.IntegerField(choices=[(0, 'Choice 1'), (1, 'Choice 2'), (2, 'Choice 3'), (3, 'Choice 4')])),
                ('enabled', models.BooleanField(verbose_name='Action enabled. If true row can be edited.')),
                ('uuid_field', models.UUIDField(default=uuid.UUID('86001506-ffaf-11e9-a4bc-645d86dd59b4'), help_text='Uuid v1', verbose_name='Uuid field')),
            ],
        ),
    ]
