# Generated by Django 2.2.13 on 2020-09-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0003_filter_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicfields",
            name="password_field",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
