# Generated by Django 2.2.1 on 2019-10-30 13:26
import random
from random import randint

from django.db import migrations

from examples.models import ConfirmAction


def populate_confirm_action_table(apps, schema_editor):
    for i in range(0, 20):
        ConfirmAction.objects.create(
            action_type=randint(0, 4),
            action_name='action name %d' % i,
            enabled=random.choice([True, False])
        )


class Migration(migrations.Migration):
    dependencies = [
        ('examples', '0003_confirmaction'),
    ]

    operations = [
        migrations.RunPython(populate_confirm_action_table),
    ]
