# Generated by Django 3.0.10 on 2020-09-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0004_basicfields_password_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="refreshtype",
            name="rich_text_field",
            field=models.TextField(blank=True, null=True),
        ),
    ]
