# Generated by Django 2.1.4 on 2018-12-11 21:45

from django.db import migrations, models
import django.db.models.deletion


def add_relation(apps, schema_editor):
    from ..models import Relation
    for i in range(1, 11):
        Relation.objects.create(name='Relation object %d' % i)


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0004_advancedfields_basicfields_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='advancedfields',
            name='hyperlinked_identity_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hyper_identity', to='examples.Relation'),
        ),
        migrations.AddField(
            model_name='advancedfields',
            name='hyperlinked_related_field',
            field=models.ManyToManyField(related_name='hyper_related', to='examples.Relation'),
        ),
        migrations.AddField(
            model_name='advancedfields',
            name='primary_key_related_field',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary', to='examples.Relation'),
        ),
        migrations.AddField(
            model_name='advancedfields',
            name='slug_related_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slug', to='examples.Relation'),
        ),
        migrations.RunPython(add_relation, lambda apps, schema_editor: None),
    ]
