# Generated by Django 2.1.1 on 2019-01-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0005_relation_advancedfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicfields',
            name='boolean_field',
            field=models.BooleanField(default=False),
        ),
    ]
