# Generated by Django 3.0.10 on 2020-09-21 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("examples", "0005_advancedfields_file_field_two"),
        ("examples", "0005_refreshtype_rich_text_field"),
    ]

    operations = []
