# Generated by Django 2.1.1 on 2019-03-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0007_refreshtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageload',
            name='choice',
            field=models.IntegerField(choices=[(1, 'Choice 1'), (2, 'Choice 2'), (3, 'Choice 3')], default=1),
        ),
        migrations.AlterField(
            model_name='hiddenfields',
            name='unit',
            field=models.CharField(blank=True, choices=[(None, 'No additional data'), ('pcs', 'Pieces'), ('wt', 'Weight'), ('cst', 'Custom')], max_length=10, null=True),
        ),
    ]
