# Generated by Django 3.1.13 on 2021-11-10 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0010_filter_rtf_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarRecurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Recurrence start')),
                ('date_to', models.DateField(verbose_name='Recurrence end')),
                ('pattern', models.IntegerField(choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Yearly')], verbose_name='Pattern')),
                ('recur', models.JSONField(verbose_name='Recur parameters')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Notification'), (2, 'Email')], verbose_name='Type')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('pattern', models.IntegerField(choices=[(1, 'Seconds'), (2, 'Minutes'), (3, 'Hours'), (4, 'Days'), (5, 'Weeks')], verbose_name='Pattern')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('colour', models.IntegerField(blank=True, null=True, verbose_name='Colour')),
                ('date_from', models.DateField(verbose_name='From')),
                ('time_from', models.TimeField(blank=True, null=True, verbose_name='')),
                ('date_to', models.DateField(verbose_name='To')),
                ('time_to', models.TimeField(blank=True, null=True, verbose_name='')),
                ('recurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='examples.calendarrecurrence', verbose_name='Recurrence')),
            ],
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['recurrence', 'date_from'], name='examples_ca_recurre_a79646_idx'),
        ),
    ]
