# Generated by Django 3.2.12 on 2023-08-11 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0011_auto_20211120_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='validated',
            name='item_flags',
            field=models.CharField(blank=True, choices=[('A', 'Alpha'), ('B', 'Beta'), ('C', 'Cama'), ('D', 'Delta')], max_length=4, validators=[django.core.validators.RegexValidator('^[ABC]*$', 'Only options A-C may be chosen', 'regex')]),
        ),
    ]
