# Generated by Django 5.0.2 on 2025-04-19 08:11

import django.core.validators
import dynamicforms.models_fields
import examples.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0011_auto_20211120_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedfields',
            name='color_field',
            field=dynamicforms.models_fields.ColorField(null=True),
        ),
        migrations.AddField(
            model_name='advancedfields',
            name='enum_choice_field',
            field=dynamicforms.models_fields.EnumChoiceField(enum=examples.models.EnumFieldChoices, null=True),
        ),
        migrations.AlterField(
            model_name='validated',
            name='item_flags',
            field=models.CharField(blank=True, choices=[('A', 'Alpha'), ('B', 'Beta'), ('C', 'Gamma'), ('D', 'Delta')], max_length=4, validators=[django.core.validators.RegexValidator('^[ABC]*$', 'Only options A-C may be chosen', 'regex')]),
        ),
        migrations.AlterField(
            model_name='validated',
            name='item_type',
            field=dynamicforms.models_fields.IntegerChoiceMigrationIgnoreField(),
        ),
    ]
