<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png">
    <HelloWorld msg="Welcome to Your Vue.js App"/>
    <dftable :key="config.uuid" :config="config"/>
  </div>
</template>

<script>
import dftable from '../../vue/src/components/dftable.vue';

import HelloWorld from './components/HelloWorld.vue';

export default {
  name: 'App',
  components: {
    HelloWorld,
    dftable,
  },
  data() {
    return {
      config: {
        uuid: '3d4bbd12-93c6-11ec-addb-1e00333c5875',
        titles: {
          table: 'Hidden fields list',
          new: 'New hidden fields object',
          edit: 'Editing hidden fields object',
        },
        columns: [{
          help_text: null,
          uuid: '3d4b47b0-93c6-11ec-addb-1e00333c5875',
          name: 'id',
          label: 'ID',
          read_only: true,
          table_classes: '',
          ordering: 'ordering asc seg-1',
          alignment: 'right',
          visibility: { table: 10, form: 5 },
          render_params: {
            form: 'DFWidgetInput',
            input_type: 'number',
            table: 'df-tablecell-plaintext',
            field_class: 'form-control',
            label_after_element: false,
            container_class: 'form-group',
          },
          allow_null: false,
          textarea: false,
        }, {
          help_text: null,
          uuid: '3d4b2f32-93c6-11ec-addb-1e00333c5875',
          name: 'df_control_data',
          label: 'Df control data',
          read_only: true,
          table_classes: '',
          ordering: '',
          alignment: 'left',
          visibility: { table: 5, form: 5 },
          render_params: {
            form: 'DFWidgetInput',
            input_type: 'text',
            table: 'df-tablecell-plaintext',
            field_class: 'form-control',
            label_after_element: false,
            container_class: 'form-group',
          },
          allow_null: false,
          textarea: false,
        }, {
          help_text: null,
          uuid: '3d4b3428-93c6-11ec-addb-1e00333c5875',
          name: 'df_prev_id',
          label: 'Df prev id',
          read_only: true,
          table_classes: '',
          ordering: '',
          alignment: 'left',
          visibility: { table: 5, form: 5 },
          render_params: {
            form: 'DFWidgetInput',
            input_type: 'text',
            table: 'df-tablecell-plaintext',
            field_class: 'form-control',
            label_after_element: false,
            container_class: 'form-group',
          },
          allow_null: false,
          textarea: false,
        }, {
          help_text: null,
          uuid: '3d4b3b8a-93c6-11ec-addb-1e00333c5875',
          name: 'row_css_style',
          label: 'Row css style',
          read_only: true,
          table_classes: '',
          ordering: '',
          alignment: 'left',
          visibility: { table: 5, form: 5 },
          render_params: {
            form: 'DFWidgetInput',
            input_type: 'text',
            table: 'df-tablecell-plaintext',
            field_class: 'form-control',
            label_after_element: false,
            container_class: 'form-group',
          },
          allow_null: false,
          textarea: false,
        }, {
          help_text: 'Enter abc to hide unit field',
          uuid: '3d4b4f08-93c6-11ec-addb-1e00333c5875',
          name: 'note',
          label: 'Note',
          read_only: false,
          table_classes: '',
          ordering: 'ordering unsorted',
          alignment: 'left',
          visibility: { table: 10, form: 10 },
          render_params: {
            form: 'DFWidgetInput',
            input_type: 'text',
            table: 'df-tablecell-plaintext',
            field_class: 'form-control',
            label_after_element: false,
            container_class: 'form-group',
            max_length: 20,
            min_length: null,
          },
          allow_null: false,
          textarea: false,
        }, {
          help_text: null,
          uuid: '3d4b567e-93c6-11ec-addb-1e00333c5875',
          name: 'unit',
          label: 'Unit',
          read_only: false,
          table_classes: '',
          ordering: 'ordering unsorted',
          alignment: 'left',
          visibility: { table: 10, form: 10 },
          render_params: {
            form: 'DFWidgetSelect',
            input_type: 'text',
            table: 'df-tablecell-plaintext',
            multiple: false,
            allow_tags: false,
            field_class: 'form-control',
            label_after_element: false,
            container_class: 'form-group',
          },
          allow_null: true,
          textarea: false,
          choices: [{ id: null, text: 'No additional data' }, { id: 'pcs', text: 'Pieces' }, {
            id: 'wt',
            text: 'Weight',
          }, { id: 'cst', text: 'Custom' }],
          allow_tags: false,
        }, {
          help_text: null,
          uuid: '3d4b5ec6-93c6-11ec-addb-1e00333c5875',
          name: 'int_fld',
          label: 'Quantity',
          read_only: false,
          table_classes: '',
          ordering: 'ordering unsorted',
          alignment: 'right',
          visibility: { table: 10, form: 10 },
          render_params: {
            form: 'DFWidgetInput',
            input_type: 'number',
            table: 'df-tablecell-plaintext',
            field_class: 'form-control',
            label_after_element: false,
            container_class: 'form-group',
          },
          allow_null: true,
          textarea: false,
        }, {
          help_text: 'Feel free to use a decimal point / comma',
          uuid: '3d4b972e-93c6-11ec-addb-1e00333c5875',
          name: 'qty_fld',
          label: 'Weight',
          read_only: false,
          table_classes: '',
          ordering: 'ordering unsorted',
          alignment: 'decimal',
          visibility: { table: 10, form: 10 },
          render_params: {
            form: 'DFWidgetInput',
            input_type: 'number',
            table: '#DFTableCellFloat',
            table_show_zeroes: true,
            step: '0.1',
            field_class: 'form-control',
            label_after_element: false,
            container_class: 'form-group',
          },
          allow_null: true,
          textarea: false,
        }, {
          help_text: 'Enter additional info here',
          uuid: '3d4ba17e-93c6-11ec-addb-1e00333c5875',
          name: 'cst_fld',
          label: 'Comment',
          read_only: false,
          table_classes: '',
          ordering: 'ordering unsorted',
          alignment: 'left',
          visibility: { table: 10, form: 10 },
          render_params: {
            form: 'DFWidgetInput',
            input_type: 'text',
            table: 'df-tablecell-plaintext',
            field_class: 'form-control',
            label_after_element: false,
            container_class: 'form-group',
            max_length: 80,
            min_length: null,
          },
          allow_null: true,
          textarea: false,
        }, {
          help_text: 'Now that you have shown me, please enter something',
          uuid: '3d4ba908-93c6-11ec-addb-1e00333c5875',
          name: 'additional_text',
          label: 'Additional text',
          read_only: false,
          table_classes: '',
          ordering: 'ordering unsorted',
          alignment: 'left',
          visibility: { table: 10, form: 10 },
          render_params: {
            form: 'DFWidgetInput',
            input_type: 'text',
            table: 'df-tablecell-plaintext',
            field_class: 'form-control',
            label_after_element: false,
            container_class: 'form-group',
            max_length: 80,
            min_length: null,
          },
          allow_null: true,
          textarea: false,
        }, {
          uuid: '',
          name: '#actions-row_end',
          label: 'Actions',
          read_only: false,
          alignment: 'left',
          table_classes: '',
          ordering: '',
          render_params: {},
          help_text: '',
          visibility: { table: 10 },
          allow_null: false,
        }],
        actions: {
          add: {
            position: 'HEADER',
            field_name: null,
            name: 'add',
            action_js: '',
            action: null,
            label: '+ Add',
            title: 'Add new record',
            icon: 'add-circle-outline',
            classes: null,
          },
          edit: {
            position: 'ROW_CLICK',
            field_name: null,
            name: 'edit',
            action_js: '',
            action: null,
            label: 'Edit',
            title: 'Edit record',
            icon: 'pencil-outline',
            classes: null,
          },
          delete: {
            position: 'ROW_END',
            field_name: null,
            name: 'delete',
            action_js: '',
            action: null,
            label: 'Delete',
            title: 'Delete record',
            icon: 'trash-outline',
            classes: null,
          },
        },
        record: null,
        filter: null,
        dialog: {
          rows: [{
            component: 'DFFormRow',
            columns: [{
              type: 'column',
              field: {
                help_text: null,
                uuid: '3d4b47b0-93c6-11ec-addb-1e00333c5875',
                name: 'id',
                label: 'ID',
                read_only: true,
                table_classes: '',
                ordering: 'ordering asc seg-1',
                alignment: 'right',
                visibility: { table: 10, form: 5 },
                render_params: {
                  form: 'DFWidgetInput',
                  input_type: 'number',
                  table: 'df-tablecell-plaintext',
                  field_class: 'form-control',
                  label_after_element: false,
                  container_class: 'form-group',
                },
                allow_null: false,
                textarea: false,
              },
            }, {
              type: 'column',
              field: {
                help_text: null,
                uuid: '3d4b2f32-93c6-11ec-addb-1e00333c5875',
                name: 'df_control_data',
                label: 'Df control data',
                read_only: true,
                table_classes: '',
                ordering: '',
                alignment: 'left',
                visibility: { table: 5, form: 5 },
                render_params: {
                  form: 'DFWidgetInput',
                  input_type: 'text',
                  table: 'df-tablecell-plaintext',
                  field_class: 'form-control',
                  label_after_element: false,
                  container_class: 'form-group',
                },
                allow_null: false,
                textarea: false,
              },
            }, {
              type: 'column',
              field: {
                help_text: null,
                uuid: '3d4b3428-93c6-11ec-addb-1e00333c5875',
                name: 'df_prev_id',
                label: 'Df prev id',
                read_only: true,
                table_classes: '',
                ordering: '',
                alignment: 'left',
                visibility: { table: 5, form: 5 },
                render_params: {
                  form: 'DFWidgetInput',
                  input_type: 'text',
                  table: 'df-tablecell-plaintext',
                  field_class: 'form-control',
                  label_after_element: false,
                  container_class: 'form-group',
                },
                allow_null: false,
                textarea: false,
              },
            }, {
              type: 'column',
              field: {
                help_text: null,
                uuid: '3d4b3b8a-93c6-11ec-addb-1e00333c5875',
                name: 'row_css_style',
                label: 'Row css style',
                read_only: true,
                table_classes: '',
                ordering: '',
                alignment: 'left',
                visibility: { table: 5, form: 5 },
                render_params: {
                  form: 'DFWidgetInput',
                  input_type: 'text',
                  table: 'df-tablecell-plaintext',
                  field_class: 'form-control',
                  label_after_element: false,
                  container_class: 'form-group',
                },
                allow_null: false,
                textarea: false,
              },
            }, {
              type: 'column',
              field: {
                help_text: 'Enter abc to hide unit field',
                uuid: '3d4b4f08-93c6-11ec-addb-1e00333c5875',
                name: 'note',
                label: 'Note',
                read_only: false,
                table_classes: '',
                ordering: 'ordering unsorted',
                alignment: 'left',
                visibility: { table: 10, form: 10 },
                render_params: {
                  form: 'DFWidgetInput',
                  input_type: 'text',
                  table: 'df-tablecell-plaintext',
                  field_class: 'form-control',
                  label_after_element: false,
                  container_class: 'form-group',
                  max_length: 20,
                  min_length: null,
                },
                allow_null: false,
                textarea: false,
              },
            }],
          }, {
            component: 'DFFormRow',
            columns: [{
              type: 'column',
              field: {
                help_text: null,
                uuid: '3d4b567e-93c6-11ec-addb-1e00333c5875',
                name: 'unit',
                label: 'Unit',
                read_only: false,
                table_classes: '',
                ordering: 'ordering unsorted',
                alignment: 'left',
                visibility: { table: 10, form: 10 },
                render_params: {
                  form: 'DFWidgetSelect',
                  input_type: 'text',
                  table: 'df-tablecell-plaintext',
                  multiple: false,
                  allow_tags: false,
                  field_class: 'form-control',
                  label_after_element: false,
                  container_class: 'form-group',
                },
                allow_null: true,
                textarea: false,
                choices: [{ id: null, text: 'No additional data' }, { id: 'pcs', text: 'Pieces' }, {
                  id: 'wt',
                  text: 'Weight',
                }, { id: 'cst', text: 'Custom' }],
                allow_tags: false,
              },
            }],
          }, {
            component: 'DFFormRow',
            columns: [{
              type: 'column',
              field: {
                help_text: null,
                uuid: '3d4b5ec6-93c6-11ec-addb-1e00333c5875',
                name: 'int_fld',
                label: 'Quantity',
                read_only: false,
                table_classes: '',
                ordering: 'ordering unsorted',
                alignment: 'right',
                visibility: { table: 10, form: 10 },
                render_params: {
                  form: 'DFWidgetInput',
                  input_type: 'number',
                  table: 'df-tablecell-plaintext',
                  field_class: 'form-control',
                  label_after_element: false,
                  container_class: 'form-group',
                },
                allow_null: true,
                textarea: false,
              },
            }],
          }, {
            component: 'DFFormRow',
            columns: [{
              type: 'column',
              field: {
                help_text: 'Feel free to use a decimal point / comma',
                uuid: '3d4b972e-93c6-11ec-addb-1e00333c5875',
                name: 'qty_fld',
                label: 'Weight',
                read_only: false,
                table_classes: '',
                ordering: 'ordering unsorted',
                alignment: 'decimal',
                visibility: { table: 10, form: 10 },
                render_params: {
                  form: 'DFWidgetInput',
                  input_type: 'number',
                  table: '#DFTableCellFloat',
                  table_show_zeroes: true,
                  step: '0.1',
                  field_class: 'form-control',
                  label_after_element: false,
                  container_class: 'form-group',
                },
                allow_null: true,
                textarea: false,
              },
            }],
          }, {
            component: 'DFFormRow',
            columns: [{
              type: 'column',
              field: {
                help_text: 'Enter additional info here',
                uuid: '3d4ba17e-93c6-11ec-addb-1e00333c5875',
                name: 'cst_fld',
                label: 'Comment',
                read_only: false,
                table_classes: '',
                ordering: 'ordering unsorted',
                alignment: 'left',
                visibility: { table: 10, form: 10 },
                render_params: {
                  form: 'DFWidgetInput',
                  input_type: 'text',
                  table: 'df-tablecell-plaintext',
                  field_class: 'form-control',
                  label_after_element: false,
                  container_class: 'form-group',
                  max_length: 80,
                  min_length: null,
                },
                allow_null: true,
                textarea: false,
              },
            }],
          }, {
            component: 'DFFormRow',
            columns: [{
              type: 'column',
              field: {
                help_text: 'Now that you have shown me, please enter something',
                uuid: '3d4ba908-93c6-11ec-addb-1e00333c5875',
                name: 'additional_text',
                label: 'Additional text',
                read_only: false,
                table_classes: '',
                ordering: 'ordering unsorted',
                alignment: 'left',
                visibility: { table: 10, form: 10 },
                render_params: {
                  form: 'DFWidgetInput',
                  input_type: 'text',
                  table: 'df-tablecell-plaintext',
                  field_class: 'form-control',
                  label_after_element: false,
                  container_class: 'form-group',
                  max_length: 80,
                  min_length: null,
                },
                allow_null: true,
                textarea: false,
              },
            }],
          }],
          actions: {
            form_init: {
              name: 'form_init',
              action_js: 'examples.hide_fields_on_show("{{ serializer.uuid }}");',
              action: null,
            },
            cancel: {
              uuid: '3d4bb16e-93c6-11ec-addb-1e00333c5875',
              element_id: 'cancel-3d4bbd12-93c6-11ec-addb-1e00333c5875',
              type: 'CANCEL',
              positions: ['dialog', 'form'],
              name: 'cancel',
              action_js: false,
              action: null,
              label: 'Cancel',
              title: 'Cancel',
              icon: null,
              classes: 'btn ml-1 btn-secondary ',
            },
            submit: {
              uuid: '3d4bb33a-93c6-11ec-addb-1e00333c5875',
              element_id: 'submit-3d4bbd12-93c6-11ec-addb-1e00333c5875',
              type: 'SUBMIT',
              positions: ['dialog', 'form'],
              name: 'submit',
              action_js: false,
              action: null,
              label: 'Save changes',
              title: 'Save changes',
              icon: null,
              classes: 'btn ml-1 btn-primary ',
            },
          },
          component_name: 'ExampleHiddenLayout',
        },
        detail_url: 'http://localhost:8000/hidden-fields/--record_id--.json',
        ordering_parameter: 'ordering',
        ordering_style: null,
        rows: {
          prev: null,
          next: null,
          results: [{
            id: '1',
            df_control_data: { row_css_style: '', actions: { edit: {}, delete: {} } },
            df_prev_id: '',
            row_css_style: '',
            note: 'demo',
            unit: 'Pieces',
            int_fld: '2',
            qty_fld: 'None',
            cst_fld: 'None',
            additional_text: 'add',
          }],
        },
        list_url: 'http://localhost:8000/hidden-fields.json',
      },
    };
  },
};
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
