name: Coverage check
on: [pull_request]
jobs:
  lint:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.13.0'
      - name: Install Dependencies
        run: npm ci
      - name: Test build
        run: npm run build-no-tsc --if-present
      - name: Run tests
        run: npm test
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: PIP install
        run: |
          pip3 install -r requirements.txt
          pip3 install coverage django_coverage_plugin
      - name: Python unittest
        run: |
          coverage run -m unittest discover tests/
      - name: Generate coverage report
        continue-on-error: true
        run: |
          coverage report -m
          coverage json
      - uses: velis74/incremental-coverage-check@python
        with:
          coverage_json: vue/dynamicforms/coverage/coverage-final.json
          py-coverage-json: coverage.json
          logging_level:
          rep-ref: python

