name: Jest Tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.20.1'
      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: npm test
